name: flutter_network_client_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  graphql: ^5.2.1
  graphql_flutter: ^5.2.0
  retrofit: ^4.9.1
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  graphql_codegen: ^2.0.0
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true
